### PR TITLE
68 container wrapper

### LINKED ISSUE #68: Provide an alternative installation procedure using containers
One way to do it would be use the [HPC container wrapper](https://github.com/CSCfi/hpc-container-wrapper) from CSC

[Updated by Ou on 20240227]
After discussion we decide to:

- [ ] Update documentation and include instructions on manual installation
- [ ] Include config template of container for Spider
- [ ] Include config template of dask, customizing the path of the container
- [ ] Make a bash file for setup, which can be executed on HPC

### PR DESCRIPTION
**Pull request by rogerkuou**
Fix #68 

- [x] Add config file for container
- [x] Add example SLURM script
- [x] Update user guide
- [x] Bash script for auto setup on remote

Tasks after merging #70 

- [x] In userguide reminder updating config file
- [x] Elaboration on how to update the env
- [x] move the description of bash setup into an upper part, separated from manual setup

### CODE REVIEW

**Comment by rogerkuou** [comment]
Hi @meiertgrootes and @fnattino, I made some changes to the user guide to include the container wrapper. I still need time for the bash file, but the user guide is finished. Feel free to try the setup steps and see if they are working.

**Comment by rogerkuou** [comment]
Update: Meiert created bash deployment script though #70 . It works well. Only more documentation in the user guide need to be added.

**Review by meiertgrootes — APPROVED** [review]
Deployment works and documentation is easily sufficient to allow users to install and troubleshoot

**Review by fnattino — APPROVED** [review]
Thank you @rogerkuou and @SarahAlidoost for adding the section on the usage of the container wrapper -  added a couple of very minor changes, but looks good to me!

**Pull request merged**
